static int f(int x) => (int)Math.Pow(x, 2) - x + 41;

static bool IsPrime(int n, int f)
{
    if (n <= 1) return false;
    if (n == 2 || f * f > n) return true;
    if (n % f == 0) return false;
    return IsPrime(n, f + 1);
}

static int FindSmallestFactor(int n) {
    for (int i = 2; i <= Math.Sqrt(n); i++)
        if (n % i == 0) return i;
    return n;
}

{
    Console.WriteLine("The numbers generated by the forula x^2-x+41 are:");
    int x = 1;
    while (true)
    {
        int num = f(x);
        if (IsPrime(num, 2))
            Console.WriteLine(num + "\tPrime");
        else
        {
            int factor = FindSmallestFactor(num);
            Console.WriteLine(num + "\tTest fails/factor=" + factor);
            Console.ReadLine();
            return; // break
        }
        x++;
    }
    // for (int x = 1; ; x++)
    // for (;;)
}